use_frameworks!

platform :ios, '13.0'

target 'PortalSwift_Example' do
  pod 'PortalSwift', :path => '../'
  pod 'GoogleSignIn', '~> 6.2'

  target 'PortalSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
