use_frameworks!

platform :ios, '13.0'

target 'PortalSwift_Example' do
  pod 'PortalSwift', :path => '../'
  pod 'GoogleSignIn', '~> 6.2'

  target 'PortalSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end
end
