use_frameworks!

platform :ios, '10.0'

target 'PortalSwift_Example' do
  pod 'PortalSwift', :path => '../'

  target 'PortalSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
