included:
  - PortalSwift
  - Cocoapods Example
  - SPM Example

excluded:
  - Pods
  - Cocoapods Example/Pods

only_rules:
  - force_unwrapping
  - force_cast

force_unwrapping:
  severity: error

force_cast:
  severity: error
