ignore:
  - "main/.swiftspm"
  - "main/Cocoapods Example"
  - "main/SPM Example"
  - "main/Sources/Frameworks"
  - "main/Sources/PortalSwift/Mocks"
  - "main/Sources/PortalSwift/Storage/GDrive/GoogleAuth.swift"
  - "main/Sources/PortalSwift/Storage/Passkeys/PasskeyAuth.swift"
  - "main/Sources/PortalSwift/Utils"
  - "main/Pods"
  - "main/Pods.xcworkspace"
  - "main/PortalSwift.xcworkspace"
  - "main/Tests"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
