ignore:
  - "**/.swiftspm"
  - "**/Cocoapods Example"
  - "**/SPM Example"
  - "**/Sources/Frameworks"
  - "**/Sources/PortalSwift/Mocks"
  - "**/Pods"
  - "**/Pods.xcworkspace"
  - "**/PortalSwift.xcworkspace"
  - "**/Tests"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
