ignore:
  - "**/Frameworks"
  - "**/GoogleAuth.swift"
  - "**/MobileStorageAdapter.swift"
  - "main/Sources/PortalSwift/Mocks"
  - "**/PasskeyAuth.swift"
  - "**/PortalStorage.swift"
  - "**/Tests"
  - "main/Sources/PortalSwift/Utils"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
