ignore:
  - "main/PortalSwift/Sources/PortalSwift/Components"
  - "main/PortalSwift/Sources/PortalSwift/Mocks"
  - "main/PortalSwift/Sources/PortalSwift/Swaps"
  - "main/PortalSwift/Sources/PortalSwift/Utils"
  - "**/GoogleAuth.swift"
  - "**/MobileStorageAdapter.swift"
  - "**/PasskeyAuth.swift"
  - "**/PortalStorage.swift"
  - "**/*Types.swift"
