ignore:
  - "Sources/Frameworks"
  - "Sources/PortalSwift/Mocks"
  - "Sources/PortalSwift/Storage/GDrive/GoogleAuth.swift"
  - "Sources/PortalSwift/Storage/Passkeys/PasskeyAuth.swift"
  - "Sources/PortalSwift/Utils/*"
  - "Tests"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
