ignore:
  - "**/Frameworks"
  - "**/GoogleAuth.swift"
  - "**/MobileStorageAdapter.swift"
  - "**/Mocks"
  - "**/PasskeyAuth.swift"
  - "**/PortalStorage.swift"
  - "**/Tests"
  - "**/Utils/"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
