ignore:
  - "**/Frameworks"
  - "**/PortalSwift/Core/MobileStorageAdapter.swift"
  - "**/PortalSwift/Mocks"
  - "**/PortalSwift/Storage/GDrive/GoogleAuth.swift"
  - "**/PortalSwift/Storage/Passkeys/PasskeyAuth.swift"
  - "**/PortalSwift/Utils/*"
  - "**/Tests"
  - "**/*Types.swift"
  - "**/*.xcframework"
  - "**/*.framework"
