ignore:
  - "main/.swiftspm"
  - "main/Cocoapods Example"
  - "main/SPM Example"
  - "main/Sources/Frameworks"
  - "main/Sources/PortalSwift/Mocks"
  - "main/Pods"
  - "main/Pods.xcworkspace"
  - "main/PortalSwift.xcworkspace"
  - "main/Tests"
  - "main/*Types.swift"
  - "main/*.xcframework"
  - "main/*.framework"
