#!/bin/bash
# Run swiftformat if installed.
if which swiftformat >/dev/null; then
  swiftformat .
else
  echo "warning: SwiftFormat not installed, install it with brew install swiftformat"
fi

# Run swiftlint if installed.
# DISABLED: Disabled for now until we get to 0 force unwrapping errors.
# if which swiftlint >/dev/null; then
#   swiftlint --config .swiftlint.yml
# else
#   echo "warning: SwiftLint not installed, install it with brew install swiftlint"
# fi
