//
//  PortalErrorCodes.swift
//  PortalSwift
//
//  Created by Blake Williams on 3/8/23.
//

import Foundation

public enum PortalErrorCodes: Int {
  case FAILED_TO_SEND_SIGN_REQUEST = 200
  case BAD_REQUEST = 201
  case INVALID_API_KEY = 202
  case NOT_FOUND = 203
  case FAILED_TO_RECEIVE_101_STATUS_CODE = 204
  case FAILED_TO_CREATE_WEBSOCKET = 205
  case DKG_NETWORK_ERROR = 206
  case FAILED_TO_READ_PARTIAL_PUBLIC_KEY_FROM_SOCKET = 207
  case FAILED_TO_WRITE_PARTIAL_PUBLIC_KEY_TO_SOCKET = 208
  case FAILED_TO_READ_FROM_SOCKET_IN_LISTEN = 209
  case REFRESH_NETWORK_ERROR = 210
  case SIGNING_NETWORK_ERROR = 211
  case FAILED_TO_COMPUTE_ETH_ADDRESS = 300
  case FAILED_TO_CREATE_SHARE_OBJECT = 301
  case INCORRECT_INPUT_TO_SIGN = 302
  case FAILED_TO_CONVERT_PUBLIC_KEY_BYTES = 303
  case FAILED_TO_COMPUTE_SIGNATURE = 304
  case FAILED_TO_PARSE_INPUT_SHARE_OBJECT = 305
  case INCORRECT_SHARE_OBJECT_TYPE = 306
  case FAILED_TO_CONVERT_STRING_TO_BIG_INT = 307
  case FAILED_TO_POPULATE_TRANSACTION = 308
  case FAILED_TO_BUILD_MESSAGE = 309
  case UNSUPPORTED_ETH_METHOD = 310
  case NODE_RPC_ERROR = 311
  case FAILED_TO_INITIALIZE_PUBLIC_KEY = 312
  case FAILED_TO_CALCULATE_SELF_PUBLIC_KEY = 313
  case FAILED_TO_UNMARSHAL_PARTIAL_PUBLIC_KEY_FROM_SOCKET = 314
  case FAILED_TO_MARSHAL_PARTIAL_PUBLIC_KEY = 315
}
