//
//  PortalErrorCodes.swift
//  PortalSwift
//
//  Created by Blake Williams on 3/8/23.
//

import Foundation

public enum PortalErrorCodes: Int {
  // MPC Errors
  case INVALID_RANK_AND_THRESHOLD = 100
  case FAILED_TO_START_DKG = 101
  case FAILED_TO_FINISH_DKG = 102
  case FAILED_TO_CONVERT_DKG_RESULT = 103
  case FAILED_TO_START_RESHARE = 104
  case FAILED_TO_FINISH_RESHARE = 105
  case FAILED_TO_CONVERT_RESHARE_RESULT = 106
  case FAILED_TO_START_SIGN = 107
  case FAILED_TO_FINISH_SIGN = 108
  case FAILED_TO_CONVERT_SIGN_RESULT = 109
  case DKG_PROCESS_ERROR = 110
  case FAILED_TO_PARSE_SOCKET_MESSAGE = 111
  case FAILED_TO_ADD_MESSAGE_TO_CHANNEL = 112
  case REFRESH_SHARE_MISMATCH = 113
  case REFRESH_PROCESS_ERROR = 114
  case FAILED_TO_GET_PAILLIER_KEY = 115
  case SIGNING_SHARE_MISMATCH = 116
  case SIGNING_PROCESS_ERROR = 117

  // Network Errors
  case FAILED_TO_SEND_SIGN_REQUEST = 200
  case BAD_REQUEST = 201
  case INVALID_API_KEY = 202
  case NOT_FOUND = 203
  case FAILED_TO_RECEIVE_101_STATUS_CODE = 204
  case FAILED_TO_CREATE_WEBSOCKET = 205
  case DKG_NETWORK_ERROR = 206
  case FAILED_TO_READ_PARTIAL_PUBLIC_KEY_FROM_SOCKET = 207
  case FAILED_TO_WRITE_PARTIAL_PUBLIC_KEY_TO_SOCKET = 208
  case FAILED_TO_READ_FROM_SOCKET_IN_LISTEN = 209
  case REFRESH_NETWORK_ERROR = 210
  case SIGNING_NETWORK_ERROR = 211
  case BLOCKED_ADDRESS_BY_DEFAULT = 212
  case BLOCKED_ADDRESS_BY_ENVIRONMENT = 213

  // General Errors
  case FAILED_TO_COMPUTE_ETH_ADDRESS = 300
  case FAILED_TO_CREATE_SHARE_OBJECT = 301
  case INCORRECT_INPUT_TO_SIGN = 302
  case FAILED_TO_CONVERT_PUBLIC_KEY_BYTES = 303
  case FAILED_TO_COMPUTE_SIGNATURE = 304
  case FAILED_TO_PARSE_INPUT_SHARE_OBJECT = 305
  case INCORRECT_SHARE_OBJECT_TYPE = 306
  case FAILED_TO_CONVERT_STRING_TO_BIG_INT = 307
  case FAILED_TO_POPULATE_TRANSACTION = 308
  case FAILED_TO_BUILD_MESSAGE = 309
  case UNSUPPORTED_ETH_METHOD = 310
  case NODE_RPC_ERROR = 311
  case FAILED_TO_INITIALIZE_PUBLIC_KEY = 312
  case FAILED_TO_CALCULATE_SELF_PUBLIC_KEY = 313
  case FAILED_TO_UNMARSHALL_PARTIAL_PUBLIC_KEY_FROM_SOCKET = 314
  case FAILED_TO_MARSHAL_PARTIAL_PUBLIC_KEY = 315
  case UNSUPPORTED_MPC_PROTOCOL = 316

  // Encrypt/Decrypt Errors
  case FAILED_TO_CREATE_RANDOM_DEK_BYTES = 400
  case FAILED_TO_CREATE_CIPHER_BLOCK = 401
  case FAILED_TO_CREATE_GCM_CIPHER = 402
  case FAILED_TO_READ_NONCE_INTO_BUFFER = 403
  case FAILED_TO_DECODE_KEY_HEX_STRING = 404
  case FAILED_TO_DECODE_CIPHER_HEX_STRING = 405
  case FAILED_TO_GET_NONCE_SIZE = 406
  case FAILED_TO_DECRYPT_CIPHER = 407
}
