// Objective-C API for talking to github.com/portal-hq/mpc/client/mobile Go package.
//   gobind -lang=objc github.com/portal-hq/mpc/client/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileCggmpBackup;
@class MobileCustodian;
@class MobileEjectResult;
@class MobileFormattedShares;
@class MobileGetMeErrorType;
@class MobileGetMeResponse;
@class MobileGetMeResult;
@class MobileShareData;

@interface MobileCggmpBackup : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull clientId;
@property (nonatomic) NSString* _Nonnull custodianId;
@property (nonatomic) NSString* _Nonnull x;
@property (nonatomic) NSString* _Nonnull y;
@property (nonatomic) NSString* _Nonnull clientBk;
@property (nonatomic) NSString* _Nonnull serverBk;
@property (nonatomic) NSString* _Nonnull share;
@property (nonatomic) NSString* _Nonnull clientPartialPubKey_x;
@property (nonatomic) NSString* _Nonnull clientPartialPubKey_y;
@property (nonatomic) NSString* _Nonnull serverPartialPubKey_x;
@property (nonatomic) NSString* _Nonnull serverPartialPubKey_y;
@property (nonatomic) NSString* _Nonnull yClient_x;
@property (nonatomic) NSString* _Nonnull yClient_y;
@property (nonatomic) NSString* _Nonnull yServer_x;
@property (nonatomic) NSString* _Nonnull yServer_y;
@property (nonatomic) NSString* _Nonnull pailler_p;
@property (nonatomic) NSString* _Nonnull pailler_q;
@property (nonatomic) NSString* _Nonnull ssid;
@property (nonatomic) NSString* _Nonnull pedersenClient_n;
@property (nonatomic) NSString* _Nonnull pedersenClient_s;
@property (nonatomic) NSString* _Nonnull pedersenClient_t;
@property (nonatomic) NSString* _Nonnull pedersenServer_n;
@property (nonatomic) NSString* _Nonnull pedersenServer_s;
@property (nonatomic) NSString* _Nonnull pedersenServer_t;
@end

@interface MobileCustodian : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull name;
@end

@interface MobileEjectResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
// skipped field EjectResult.Error with unsupported type: github.com/portal-hq/mpc/errorcodes.Payload

@end

/**
 * FormattedShares represents the structure of the formatted shares
 */
@interface MobileFormattedShares : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) MobileShareData* _Nullable secP256K1;
@property (nonatomic) MobileShareData* _Nullable eD25519;
@end

@interface MobileGetMeErrorType : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GetMeErrorType.Code with unsupported type: uint16

@property (nonatomic) NSString* _Nonnull message;
@end

@interface MobileGetMeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull backupStatus;
// skipped field GetMeResponse.Custodian with unsupported type: github.com/portal-hq/mpc/client/mobile.Custodian

@property (nonatomic) NSString* _Nonnull signingStatus;
@end

@interface MobileGetMeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GetMeResult.Data with unsupported type: github.com/portal-hq/mpc/client/mobile.GetMeResponse

// skipped field GetMeResult.Error with unsupported type: github.com/portal-hq/mpc/client/mobile.GetMeErrorType

@end

/**
 * ShareData represents the structure of a single share
 */
@interface MobileShareData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull share;
@end

FOUNDATION_EXPORT NSString* _Nonnull MobileBackup(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileBackupEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileBackupSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

// skipped function CreateEjectResult with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull MobileDecrypt(NSString* _Nullable key, NSString* _Nullable dkgCipherText);

FOUNDATION_EXPORT NSString* _Nonnull MobileDecryptWithPassword(NSString* _Nullable password, NSString* _Nullable dkgCipherText);

FOUNDATION_EXPORT NSString* _Nonnull MobileEjectWalletAndDiscontinueMPC(NSString* _Nullable clientDkgResult, NSString* _Nullable serverDkgResult);

FOUNDATION_EXPORT NSString* _Nonnull MobileEjectWalletAndDiscontinueMPCEd25519(NSString* _Nullable clientDkgResult, NSString* _Nullable serverDkgResult);

FOUNDATION_EXPORT NSString* _Nonnull MobileEncrypt(NSString* _Nullable value);

FOUNDATION_EXPORT NSString* _Nonnull MobileEncryptWithPassword(NSString* _Nullable value, NSString* _Nullable password);

FOUNDATION_EXPORT NSString* _Nonnull MobileFormatShares(NSString* _Nullable sharesJSON);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerate(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerateEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerateSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetCustodianIdClientIdHashes(NSString* _Nullable custodianIdClientIdJSON);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetMe(NSString* _Nullable url, NSString* _Nullable token);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetVersion(void);

// skipped function RecoverAndFormatPrivateKey with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverAndFormatPrivateKeyEd25519(NSString* _Nullable clientDkgResult, NSString* _Nullable serverDkgResult, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverAndFormatPrivateKeySecp256k1(NSString* _Nullable clientDkgResult, NSString* _Nullable serverDkgResult, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackup(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackupEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackupSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigning(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigningEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigningSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileSign(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable method, NSString* _Nullable params, NSString* _Nullable rpcURL, NSString* _Nullable chainId, NSString* _Nullable metadataStr);

#endif
