// Objective-C API for talking to github.com/portal-hq/mpc/client/mobile Go package.
//   gobind -lang=objc github.com/portal-hq/mpc/client/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileCustodian;
@class MobileGetMeResponse;
@class MobileGetMeResult;
@class MobileMetaResult;
@class MobileMetadata;

@interface MobileCustodian : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull name;
@end

@interface MobileGetMeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull backupStatus;
// skipped field GetMeResponse.Custodian with unsupported type: github.com/portal-hq/mpc/client/mobile.Custodian

@property (nonatomic) NSString* _Nonnull signingStatus;
@end

@interface MobileGetMeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GetMeResult.Data with unsupported type: github.com/portal-hq/mpc/client/mobile.GetMeResponse

@end

@interface MobileMetaResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field MetaResult.Metrics with unsupported type: *github.com/portal-hq/mpc/client/core.Metrics

@end

@interface MobileMetadata : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull backupMethod;
@property (nonatomic) NSString* _Nonnull clientPlatform;
@property (nonatomic) NSString* _Nonnull clientPlatformVersion;
// skipped field Metadata.IsMultiBackupEnabled with unsupported type: *bool

@property (nonatomic) NSString* _Nonnull mpcServerVersion;
@property (nonatomic) BOOL optimized;
@property (nonatomic) NSString* _Nonnull curve;
@property (nonatomic) NSString* _Nonnull signingScheme;
@property (nonatomic) NSString* _Nonnull chainId;
@property (nonatomic) NSString* _Nonnull reqId;
@property (nonatomic) BOOL isRaw;
@property (nonatomic) NSString* _Nonnull mpcClientHeader;
@property (nonatomic) NSString* _Nonnull signatureApprovalMemo;
@property (nonatomic) BOOL sponsorGas;
@property (nonatomic) BOOL connectionTracingEnabled;
/**
 * Custom unmarshalling to set the default value of Optimized and SponsorGas to true
 */
- (BOOL)unmarshalJSON:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull const MobileCurrentClientVersion;

FOUNDATION_EXPORT NSString* _Nonnull MobileBackup(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileBackupEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileBackupSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileDecrypt(NSString* _Nullable key, NSString* _Nullable encryptedText);

FOUNDATION_EXPORT NSString* _Nonnull MobileDecryptWithPassword(NSString* _Nullable password, NSString* _Nullable encryptedText);

FOUNDATION_EXPORT NSString* _Nonnull MobileEjectWalletAndDiscontinueMPC(NSString* _Nullable clientShareStr, NSString* _Nullable custodianShareStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileEjectWalletAndDiscontinueMPCEd25519(NSString* _Nullable clientShareStr, NSString* _Nullable custodianShareStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileEncrypt(NSString* _Nullable value);

FOUNDATION_EXPORT NSString* _Nonnull MobileEncryptWithPassword(NSString* _Nullable value, NSString* _Nullable password);

FOUNDATION_EXPORT NSString* _Nonnull MobileFormatShares(NSString* _Nullable sharesJSON);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerate(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerateEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileGenerateSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

/**
 * TODO: Does this function have to be part of the mobile client?
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetCustodianIdClientIdHashes(NSString* _Nullable custodianIdClientIdJSON);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetMe(NSString* _Nullable url, NSString* _Nullable token);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetVersion(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackup(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackupEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverBackupSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigning(NSString* _Nullable clientAPIKey, NSString* _Nullable addr, NSString* _Nullable dkgResult, NSString* _Nullable apiAddr, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigningEd25519(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileRecoverSigningSecp256k1(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable portalApiUrl, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileSign(NSString* _Nullable clientAPIKey, NSString* _Nullable mpcAddr, NSString* _Nullable shareStr, NSString* _Nullable method, NSString* _Nullable params, NSString* _Nullable rpcURL, NSString* _Nullable chainId, NSString* _Nullable metadataStr);

FOUNDATION_EXPORT NSString* _Nonnull MobileWebsocketHealthcheck(NSString* _Nullable addr);

#endif
