
// Objective-C API for talking to the following Go packages
//
//	github.com/portal-hq/mpc/client/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mpc_FRAMEWORK_H__
#define __Mpc_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
