use_frameworks!

platform :ios, '13.0'

project './Cocoapods Example.xcodeproj'
workspace '../PortalSwift.xcworkspace'

install! 'cocoapods', :deterministic_uuids => false

target 'Cocoapods Example' do
  pod 'PortalSwift', :path => '../', :testspecs => ['Tests']
  pod 'GoogleSignIn', '~> 6.2'

  target 'Cocoapods E2E Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end
end
