name: Handle Release Status
on:
  workflow_run:
    workflows: ["Publish the sdk version"]
    types:
      - completed

jobs:
  handle_workflow_status:
    runs-on: ubuntu-latest

    steps:
      - name: Slack - send failed status of version workflow
        if: ${{github.event.workflow_run.conclusion == 'failure'}}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "Title": "**Publishing the swift sdk version failed**",
            "Body": "Please check the GH Action Console. https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}",
            "Status": "Failure"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
