name: Tag the sdk version
on:
  push:
    branches:
      - main

jobs:
  tag_pod_version:
    runs-on: ubuntu-latest
    env:
      IS_NEW_VERSION: false
      CURRENT_VERSION: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag podspec version
        run: |
          # Set your podspec file name
          PODSPEC_FILE="PortalSwift.podspec"

          # Get current version from podspec file
          CURRENT_VERSION=$(grep -E "s.version\s*=\s*'.*'" $PODSPEC_FILE | sed -E "s/^ *s.version *= *'(.*)'/\1/")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          # Get latest git tag version
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

          # Compare the versions and create a new tag if necessary
          if [ "$CURRENT_VERSION" != "$LATEST_TAG" ]; then
            echo "IS_NEW_VERSION=true" >> $GITHUB_ENV
            git config --local user.name "portal-release-bot"
            git config --local user.email "release-bot@portalhq.io"
            git tag -a $CURRENT_VERSION -m "Version $CURRENT_VERSION"
            git push origin $CURRENT_VERSION
          else
            echo "The podspec version ($CURRENT_VERSION) is equal to the latest tag version ($LATEST_TAG). No new tag needed."
          fi

      - name: Slack - send pod published
        if: ${{ env.IS_NEW_VERSION  == 'true' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "Title": "Swift SDK Published",
            "Body": "The Swift SDK has been published with version: ${{ env.CURRENT_VERSION }}.\n",
            "Status": "Success"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack - send pod not published
        if: ${{ env.IS_NEW_VERSION  == 'false' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "Title": "Swift SDK Not Published",
            "Body": "The podspec version ${{ env.CURRENT_VERSION }} is equal to the latest tag version. No new tag needed",
            "Status": "Success"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
