name: Build and Upload to Muuktest

on:
  push:
    branches:
      - release-candidate

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app

    - name: Build the app
      run: xcodebuild -scheme "SPM Example" -archivePath ${{ github.workspace }}/build/SPMExample.xcarchive archive

    - name: Export the app
      run: |
        xcodebuild -exportArchive \
        -archivePath ${{ github.workspace }}/build/SPMExample.xcarchive \
        -exportPath ${{ github.workspace }}/build \
        -exportOptionsPlist <(echo '
        {
          "method": "app-store",
          "teamID": "WTQ4Q66FY6",
          "provisioningProfiles": {
            "io.portalhq.ios.SPM-Example": "io.portalhq.ios.SPM-Example1"
          },
          "signingStyle": "automatic",
          "compileBitcode": true,
          "thinning": "<none>"
        }')

    - name: Rename exported IPA file
      run: mv ${{ github.workspace }}/build/SPM\ Example.ipa ${{ github.workspace }}/build/SPMExample.ipa

    - name: Get upload URL
      id: get_upload_url
      run: |
        response=$(curl -H --location 'https://11mi38nzh1.execute-api.us-east-2.amazonaws.com/v1/uploadFile' \
          --header 'x-api-key: ***REMOVED***' \
          --header 'Content-Type:application/json' \
          --data '{"filename": "SPMExample.ipa"}')
        echo "response=$response" >> $GITHUB_ENV
        uploadURL=$(echo "$response" | grep -o '"uploadURL": *"[^"]*"' | sed 's/"uploadURL": "//' | sed 's/"$//')
        echo "uploadURL=$uploadURL" >> $GITHUB_ENV

    - name: Upload the app
      run: |
        curl --location --request PUT ${{ env.uploadURL }} \
          --header 'Content-Type: application/octet-stream' \
          --data-binary '@${{ github.workspace }}/build/SPMExample.ipa'
