name: Update the sdk version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the SDK to release"
        required: true
        type: string

jobs:
  release_sdk:
    runs-on: macos-latest
    steps:
      - name: Checkout swift repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Update version in podspec
        run: |
          cd ${{ github.workspace }}/main
          export PODSPEC_FILE="PortalSwift.podspec"
          export NEW_VERSION="${{ inputs.version }}"
          sed -i.bak -E "s/^( *s.version *= *).*/\1'$NEW_VERSION'/" "$PODSPEC_FILE"
          rm "$PODSPEC_FILE.bak"
          cat "$PODSPEC_FILE"

      - name: Open PR for Swift repo
        id: cpr
        uses: portal-hq/create-pull-request@v5
        with:
          path: main
          token: ${{ secrets.GH_PAT }}
          branch: "release"
          branch-suffix: short-commit-hash
          committer: portal-release-bot <release-bot@portalhq.io>
          author: portal-release-bot <release-bot@portalhq.io>
          delete-branch: true
          title: "SDK Release ${{ inputs.version }}"
          body: "This PR contains the updated version for the SDK: ${{ inputs.version }}"
          labels: "Release"

      - name: Checkout swift repo
        uses: actions/checkout@v2
        with:
          path: main
          ref: "release-candidate"

      - name: Update version in podspec
        run: |
          cd ${{ github.workspace }}/main
          export PODSPEC_FILE="PortalSwift.podspec"
          export NEW_VERSION="${{ inputs.version }}"
          sed -i.bak -E "s/^( *s.version *= *).*/\1'$NEW_VERSION'/" "$PODSPEC_FILE"
          rm "$PODSPEC_FILE.bak"
          cat "$PODSPEC_FILE"

      - name: Open PR for Swift repo (release-candidate)
        id: cprRc
        uses: portal-hq/create-pull-request@v5
        with:
          path: main
          token: ${{ secrets.GH_PAT }}
          branch: "release-rc"
          branch-suffix: short-commit-hash
          committer: portal-release-bot <release-bot@portalhq.io>
          author: portal-release-bot <release-bot@portalhq.io>
          delete-branch: true
          title: "SDK Release ${{ inputs.version }} for (release-candidate) "
          body: "This PR contains the updated version for the SDK: ${{ inputs.version }}"
          labels: "Release"

      - name: Slack - send version updated message
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "Title": "Swift SDK Version Updated",
            "Body": "To complete the release for version: ${{ inputs.version }}.\n\n Please approve these PRs:\n `main`: ${{ steps.cpr.outputs.pull-request-url }}\n\n `release-candidate`: ${{ steps.cprRc.outputs.pull-request-url }}\n",
            "Status": "Success"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
